name: Thecloudprojects Static Web Apps CI/CD

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-gentle-ocean-0a263fd10-variable-group

  steps:
  - checkout: self
    submodules: true
    displayName: Checkout repo

  - task: AzureStaticWebApp@0
    displayName: Build & Deploy
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_OCEAN_0A263FD10)
      app_location: "/"
      api_location: ""
      output_location: "docs/.vitepress/dist"
      app_build_command: "rm -rf node_modules package-lock.json && npm install && npm run docs:build"

